### ISSUE TITLE
Changing exit names for test and match test

### ISSUE THREAD

**Issue by shaniceabigail** [CS2103-AY1819S1-W12-3/main#81]
3VIA currently requires the command **exit** to open-ended tests, match tests, and to exit the programme. 

Can we consider changing the command to exit the tests so that we don't confuse the users.

<img width="765" alt="screen shot 2018-10-18 at 12 32 21 am" src="https://user-images.githubusercontent.com/28746253/47101730-7f12b200-d26d-11e8-82c8-4e3008859f91.png">
<img width="729" alt="screen shot 2018-10-18 at 12 32 29 am" src="https://user-images.githubusercontent.com/28746253/47101745-876aed00-d26d-11e8-8f7f-31262e63f4dd.png">
<img width="303" alt="screen shot 2018-10-18 at 12 32 37 am" src="https://user-images.githubusercontent.com/28746253/47101746-876aed00-d26d-11e8-85ce-09393c9f7def.png">

**Comment by JunWei96** [comment]
Hi Shanice, thanks for pointing out the potential confusion! Instead of creating a new command, would it be better to update section 3.16. of the User Guide? To make it clear that when `exit` is executed during a test stage, it will exit from the test instead of the program. And if the user wants to exit from the program, the user can just type `exit` one more time. By doing so, the user would have 1 less command to remember too.

@junhui2778 , what are your thoughts on this?

**Comment by shaniceabigail** [comment]
Hi Junwei, I was thinking more of a "back" or "back to menu" to prevent confusion. Otherwise, if it's a hassle, I think it will be great to clarify in 3.16. of the User Guide as you've mentioned. 

Perhaps the UI can also help to determine which page the user is on.

**Comment by shaniceabigail** [comment]
I see, then I'll make amendments to clarify this in the user guide. Thanks for the insight JunWei!
